{% set version = "1.2.2" %}

package:
  name: galario
  version: {{ version }}

source:
  url: https://github.com/mtazzari/galario/archive/v{{ version }}.tar.gz
  sha256: 51ef9d64bfc4a7f5d62371fa8b9d094838485114d582ec7d038d7821454a00c2

build:
  number: 1004
  skip: true  # [win]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - fftw
  host:
    - python
    - fftw
    - cython
    - numpy
    - pytest
    - scipy
  run:
    - fftw
    - python
    - {{ pin_compatible('numpy') }}
    - scipy

test:
  requires:
    - pytest
  imports:
    - galario
  source_files:
    - python/test_galario.py
    - python/utils.py
  commands:
    - test -d ${PREFIX}/
    - test ${PREFIX}/include/galario.h
    - test ${PREFIX}/lib/libgalario{{ SHLIB_EXT }}  # [not win]
    - cd python && py.test test_galario.py

about:
  home: https://github.com/mtazzari/galario
  license: LGPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Gpu Accelerated Library for Analysing Radio Interferometer Observations'
  description: |
    galario is a library that exploits the computing power of modern graphic
    cards (GPUs) to accelerate the comparison of model predictions to radio
    interferometer observations. Namely, it speeds up the computation of the
    synthetic visibilities given a model image (or an axisymmetric brightness
    profile) and their comparison to the observations.
  doc_url: https://mtazzari.github.io/galario/
  dev_url: https://github.com/mtazzari/galario

extra:
  recipe-maintainers:
    - fredRos
    - mtazzari
