{% set name = "galario" %}
{% set version = "1.0.3" %}
{% set github = "https://github.com/mtazzari/galario" %}
{% set sha256 = "7f72885bfbdbc02ff2daf9a05471a80518ee396edb5dc07d1c1fb3a1d2608d1e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: {{ github }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - cmake
    - fftw
    - gcc  # [osx]
    - python
    - cython
    - numpy 1.11.*
    - pytest
    - scipy
  run:
    - fftw
    - libgcc  # [osx]
    - python
    - numpy >=1.11
    - scipy

test:
  requires:
    - pytest
  imports:
    - galario
  source_files:
    - python/test_galario.py
    - python/utils.py
  commands:
    - test -d ${PREFIX}/
    - test ${PREFIX}/include/galario.h
    - test ${PREFIX}/lib/libgalario.so  # [linux]
    - test ${PREFIX}/lib/libgalario.dylib  # [osx]
    - cd python && py.test test_galario.py

about:
  home: {{ github }}
  license: LGPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Gpu Accelerated Library for Analysing Radio Interferometer Observations'
  description: |
    galario is a library that exploits the computing power of modern graphic
    cards (GPUs) to accelerate the comparison of model predictions to radio
    interferometer observations. Namely, it speeds up the computation of the
    synthetic visibilities given a model image (or an axisymmetric brightness
    profile) and their comparison to the observations.
  doc_url: https://mtazzari.github.io/galario/
  dev_url: {{ github }}

extra:
  recipe-maintainers:
    - fredRos
    - mtazzari
