travis:
  secure:
    BINSTAR_TOKEN: QB+IRumjWm1ycfiMs8rFO2LfxLZFK1+VbbUPvrVN98s79CZu7HrG/Qc4uutL1NixbGGybEm6AzBcVW2ug5+vOcZkl4mxDyzmzoB/1Lx9C1MQEViPxnkIWuzCRvvZM3i5l24H34otQD02PkhNKs29Gx73Xf8eydH70DrrHzMIEmdjUhjTBidanK5C/fEZRDPUAS+c/zTw7uY9rMupwrkgkE65hEV2VWie/VemkgByuAQoxl9lQBs/6dSh0L4uKW+sbHVPDk6ArLTSh+099iLAdwTwgBqQFF6IfiT3DgLTZVnYYj2L+jO0dgSaXlYet3/0IJgzMqrQLUI01r8qEGyn+e5Zv5QIpklLgfw2fndmYWwVbMDOxMq/kLXGuZxu/yicgCTUr4Y6A1of99gKsDpgsqY1DoB4x7Zzb4GhD3HTTtCJ2aMtFCMTnAd4FVDasLY4ju1pvzIUN1YU1l484XamSCSEXhR+vE4gg5Sh/xKPez3r/yhlb6XPywda86eaWivvVZ/o6eoTCjirRPMzmjR90zKwQCE8H3YLQPYBsnrLFENzzLd82t7EFkhPOlwc+NOJ/Xu1Oz1r8suR+lJ+YFh0xyDY1jInTswCT/kSB5muNf2x1pzgWfiwUEXh33CaGe0nCF24GiN/xM/u1yG2fEcEgO8FqFNvSFVq6gNLdpzn6r4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
