travis:
  secure:
    BINSTAR_TOKEN: Rctg6SE/9id/rm9sMqG9tro5OBi6FnRnQXfLoAD5ZjHrFC9JARrrOV3D4+wMv53bQ9ryiawJgXijFKLCeg7uiw/awySYvAEjVh1UunToR/4tyXwb+eBdXc/utfQsMttNpK0I0a6+Nc7ANxZS4n211tnGm2VzWbTO8wU4gOKbb/cB4Zeg5ncJxNUyPVGznn+sEHVuhZv2vhrKETujbmbdxqYKM7jEiEHcgUiigalUzj5/1+b+dsLhbeSZQI2Xrh0iHPSm88r5Y4NZWROaxHXHExZJ9AjzAYgWnCrnbD2VfHuyGSIdvPCLR3PoVKsHXiGvfLODZGvTtRBIqsKPY4yDOpTf2Y4Bz/0HRtwPjZsDoL8/7XksQ7fzQcCL2/55IYHfMEB17FL0wxULBjwqK0M7AL7dUvH3Q+J5vKhssn74V/wuXXJo2TWSs7Qyd+WhEenI2cahSEqjvgyznrvg8lD27KUBtzeBYmfCRIphDP1iCIyALhhdYV4NvABw+xNHeWk9gcPXtKnk3vClledwdac4xTpWNMUYGSudajthslcMyTjtT8wN6EVA1C35fxfkJx/SRwlq50aNYXwSkePOk+E36ca/JqZeJ3QpGe48yWQ+CxltaqUDgkyUyyAlcLnxHbnz34wBe6xnQbS/XUkCWPO/k1Z5h3PkGNMcMhFH7B1DoiM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
